FROM ubuntu:latest

RUN apt update; apt install -y wget
WORKDIR /home
RUN wget https://go.dev/dl/go1.12.2.linux-amd64.tar.gz; tar -C /usr/local -xzf go1.12.2.linux-amd64.tar.gz; rm go1.12.2.linux-amd64.tar.gz
RUN apt-get install -y gcc sqlite3 python3 python3-pip
RUN pip3 install tqdm regex

ENV PATH=$PATH:/usr/local/go/bin
COPY $PWD/data/go-workspace /home/go-workspace
ENV GOPATH=/home/go-workspace

RUN go version; python3 --version
RUN cd /home/go-workspace/src/php-cg/scan-project; go build

COPY $PWD/webapp/ /home/webapp
COPY $PWD/run.sh /home/

RUN chmod +x run.sh

ENTRYPOINT ["/home/run.sh"]
